# Generated by Django 4.1.4 on 2023-02-03 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomm', '0002_category_colour_size_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer_address',
            name='pin_code',
            field=models.IntegerField(),
        ),
    ]
