# Generated by Django 4.1.4 on 2023-02-04 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecomm', '0003_alter_customer_address_pin_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
    ]
