# Generated by Django 4.1.4 on 2023-02-04 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomm', '0005_customer_address_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='size',
            name='product_size',
            field=models.CharField(max_length=10),
        ),
    ]
