# Generated by Django 4.1.4 on 2023-02-06 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomm', '0006_alter_size_product_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_detail',
            name='product_price',
        ),
        migrations.AddField(
            model_name='product_master',
            name='product_price',
            field=models.IntegerField(null=True),
        ),
    ]
