# Generated by Django 4.1.4 on 2023-02-06 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomm', '0007_remove_product_detail_product_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slider_image_1', models.ImageField(upload_to='media/slider')),
                ('slider_image_2', models.ImageField(upload_to='media/slider')),
            ],
        ),
    ]
