# Generated by Django 4.1.4 on 2023-02-08 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecomm', '0010_orders_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='product',
        ),
    ]
