# Generated by Django 4.1.4 on 2023-02-20 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomm', '0011_remove_orders_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_detail',
            name='produc_image_1',
            field=models.ImageField(null=True, upload_to='media/products'),
        ),
        migrations.AddField(
            model_name='product_detail',
            name='produc_image_2',
            field=models.ImageField(null=True, upload_to='media/products'),
        ),
        migrations.AddField(
            model_name='product_detail',
            name='produc_image_3',
            field=models.ImageField(null=True, upload_to='media/products'),
        ),
    ]
