# Generated by Django 4.1.4 on 2023-02-20 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomm', '0012_product_detail_produc_image_1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_detail',
            name='produc_image_1',
        ),
        migrations.RemoveField(
            model_name='product_detail',
            name='produc_image_2',
        ),
        migrations.RemoveField(
            model_name='product_detail',
            name='produc_image_3',
        ),
        migrations.AddField(
            model_name='product_detail',
            name='product_image_1',
            field=models.ImageField(blank=True, null=True, upload_to='media/products'),
        ),
        migrations.AddField(
            model_name='product_detail',
            name='product_image_2',
            field=models.ImageField(blank=True, null=True, upload_to='media/products'),
        ),
        migrations.AddField(
            model_name='product_detail',
            name='product_image_3',
            field=models.ImageField(blank=True, null=True, upload_to='media/products'),
        ),
    ]
