# Generated by Django 4.1.4 on 2023-02-23 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecomm', '0013_remove_product_detail_produc_image_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_detail',
            name='prod_size',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='ecomm.size'),
        ),
        migrations.AlterField(
            model_name='product_detail',
            name='product_image_1',
            field=models.ImageField(null=True, upload_to='media/products'),
        ),
        migrations.AlterField(
            model_name='product_detail',
            name='product_image_2',
            field=models.ImageField(null=True, upload_to='media/products'),
        ),
        migrations.AlterField(
            model_name='product_detail',
            name='product_image_3',
            field=models.ImageField(null=True, upload_to='media/products'),
        ),
    ]
