# Generated by Django 4.1.4 on 2023-03-11 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecomm', '0014_alter_product_detail_prod_size_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_detail',
            name='prod_size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecomm.size'),
        ),
    ]
