# Generated by Django 4.1.4 on 2023-03-14 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomm', '0015_alter_product_detail_prod_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='colour',
            name='colour_image',
            field=models.ImageField(null=True, upload_to='media/colour_image'),
        ),
    ]
