# Generated by Django 4.1.7 on 2023-03-30 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecomm', '0016_colour_colour_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer_address',
            name='country',
        ),
        migrations.RemoveField(
            model_name='customer_address',
            name='district',
        ),
    ]
