# Generated by Django 4.1.7 on 2023-03-31 04:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecomm', '0018_alter_orders_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='payment_detail',
        ),
        migrations.AddField(
            model_name='sub_order',
            name='payment_detail',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ecomm.payment'),
        ),
    ]
